"""create gateway tables

Revision ID: 23dd71d7fb1b
Revises: 
Create Date: 2026-05-02 17:07:52.166073
"""

from alembic import op
import sqlalchemy as sa



revision = '23dd71d7fb1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_request_journals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('upstream_status', sa.String(length=64), nullable=True),
    sa.Column('upstream_reference', sa.String(length=128), nullable=True),
    sa.Column('upstream_response', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('ledger_dispatch_status', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_completion_merchant_idempotency_key'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('transaction_ledger_outbox_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_journal_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_journal_id'], ['transaction_request_journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'transaction_journal_id', name='uq_outbox_event_transaction_request')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_ledger_outbox_messages')
    op.drop_table('transaction_request_journals')
    # ### end Alembic commands ###
