"""add outbox worker indexes

Revision ID: cc41c9904567
Revises: 23dd71d7fb1b
Create Date: 2026-05-02 17:20:38.890468
"""

from alembic import op
import sqlalchemy as sa



revision = 'cc41c9904567'
down_revision = '23dd71d7fb1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_status_next_retry_at_created_at', 'transaction_ledger_outbox_messages', ['status', 'next_retry_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_status_next_retry_at_created_at', table_name='transaction_ledger_outbox_messages')
    # ### end Alembic commands ###
