"""create ledger posts table

Revision ID: a4e2e07e2121
Revises: 
Create Date: 2026-05-02 20:40:55.473876
"""

from alembic import op
import sqlalchemy as sa



revision = 'a4e2e07e2121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('debit_account_ref', sa.String(length=128), nullable=False),
    sa.Column('credit_account_ref', sa.String(length=128), nullable=False),
    sa.Column('upstream_reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_event_id', name='uq_ledger_post_source_event'),
    sa.UniqueConstraint('source_system', 'source_transaction_id', name='uq_ledger_post_source_transaction')
    )
    op.create_index('ix_ledger_posts_source_transaction_id', 'ledger_posts', ['source_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_posts_source_transaction_id', table_name='ledger_posts')
    op.drop_table('ledger_posts')
    # ### end Alembic commands ###
